<?php
/**
 * CB Adv. Search Component
 * 
 * @package    cbadvsearch
 * @subpackage Components
 * @license		GNU/GPL
 *  
 */
 
/*
	When you translate this file modify only the text in the right (after =>) on each line 
	and keep the "..." as they are now.
*/
$language_cbadvsearch = array(
	"save_the_search_form" => "Save the search form (fields and values) for later usage",
	"search_saved" => "The search was saved",
	"enter_the_name_of_the_search" => "Enter the name of the search",
	"ignore_selected_users" => "Ignore selected users from the next searches",
	"have_to_select_at_least_one_CB_user" => "Error: you have to select as least one CB user",
	"have_to_enter_the_name_of_the_search" => "Error: you have to enter the name of the search",
	"operation_successful" => "The operation was successful!",
	"operation_not_successful" => "Error: the operation was not successful!",
	
	"search_by_fields_or_cblists" => "Search by the fields or by the CB lists",
	"select_a_cblists" => "Select a CB list",
	"search_by_fields" => "search by fields",
	"search_by_cblists" => "search by CB lists",
	"search_by_fields_or_cblists_help" => "If you select the CB lists the fields you enter in the search will be ignored. You will only have one 'searchword' for all the fields.",
	"check_all" => "Check all",
	"uncheck_all" => "Uncheck all",
	"save_the_selected_results" => "Save the selected results",
	"ignore_the_selected_results" => "Ignore the selected results",

	"appears_in_the_results" => "Appears in the results",
	"the_configuration" => "Configuration", 
	"select_the_user_groups_you_want_to_search_in" => "Select the user groups you want to search in",
	"no_user_group" => "no user group",
	"show_the_searchfield" => "Show the searchfield into the frontend", 
	"content_of_the_field" => "Content of the field",
	"only_for_textfields" => "Only for textfield!", 
	"the_comparison_sign" => "The comparison sign",
	"css_class_for_this_field_in_results" => "The css class for this field in results", 
	"equal" => "equal",
	"less" => "less", 
	"less_or_equal" => "less or equal", 
	"greater" => "greater", 
	"greater_or_equal" => "greater or equal", 
	"like" => "like", 
	"edit_the_configuration" => "Edit the configuration", 
	"this_is_search_number" => "This is the search number", 
	"go_to_the_search" => "Go to the search", 
	"title_as_showed_in_search_form" => "Title (as showed in search form)", 
	"the_listing_of_the_results" => "The listing or the results",
	"the_searches_will_be_ordered_by" => "The searches will be ordered by", 
	"allow_the_users_to_select_the_listing_of_empty_fields" => "Allow the users to select the listing of empty fields", 
	"show_the_avatar_in_the_results_list" => "Show the avatar in the results list", 
	"show_the_numbers_in_the_results_list" => "Show the numbers in the results list", 
	"show_the_order_by_criteria_in_the_frontend" => "Show the \"order by\" criteria in the frontend", 
	"order_by" => "order by", 
	"list_the_empty_fields" => "List the empty fields", 
	"vertical" => "Vertical", 
	"horizontal" => "Horizontal", 
	"random_order" => "random order", 
	"random" => "random", 
	"cb_field_name" => "CB Field Name", 
	"manager" => "Manager",
	"Translator" => "Translator",
	"results_list" => "Results list", 
	"add_new_search" => "Add new search", 
	"add_new" => "Add new",
	"nnew" => "New",
	"edit" => "Edit", 
	"delete" => "Delete", 
	"close" => "Close",
	"searches_list" => "Searches list",
	"search_field" => "Search Field",
	"field" => "Field", 
	"the_name_of_the_search" => "The name of the search", 
	"the_search_number" => "The search number", 
	"the_number_of_searches" => "The number of searches", 
	"the_description_of_the_search" => "The description of the search", 
	"description" => "Beschreibung", 
	"searchable" => "Searchable", 
	"searchable_it_will_be_used_to_search" => "Searchable (it will be used to search)", 
	"publish_on_search_form" => "Publish on Search Form", 
	"order_on_search_form" => "Order on Search Form", 
	"email" => "Email", 
	"save_the_configuration" => "Save the configuration", 
	"save" => "Save", 
	"yes" => "yes", 
	"no" => "no", 
	"search_criteria" => "The search criteria", 
	"cancel" => "Cancel",
	"details" => "Details", 
	"label" => "Label", 
	"translation" => "Translation", 
	"select" => "Select", 
	"search_results" => "Search results",
	"results_found" => "results found",
	"no_results_found" => "No Results Found", 
	"ascendent" => "ascendent", 
	"descendent" => "descendent", 
	"view_details" => "View Details",
	"search_keyword" => "Search keyword", 
	"search" => "Suche", 
	"select_a_language" => "Select a language", 
	"the_language" => "The language", 
	"language_translation" => "Language translation", 
	"variable" => "Variable", 
	"current_value" => "Current value",
	"original_value_english" => "Original value (english)",
	
	"january" => "january",
	"february" => "february",
	"march" => "march",
	"april" => "april",
	"may" => "may",
	"june" => "june",
	"july" => "july",
	"august" => "august",
	"september" => "september",
	"octomber" => "octomber",
	"november" => "noiember",
	"december" => "december",
		
	"monday" => "Monday",
	"tuesday" => "Tuesday",
	"wednesday" => "Wednesday",
	"thursday" => "Thursday",
	"friday" => "Friday",
	"saturday" => "Saturday",
	"sunday" => "Sunday"
);
DEFINE('_UE_SOME_INSTRUMENT','Some');
?>